spring.application.name=spring-boot-learning
server.port=8082

spring.datasource.url=jdbc:h2:mem:springbootlearningdb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop

# REST response olusturulurken persistence context'in acik kalmasini engeller.
spring.jpa.open-in-view=false
